var hierarchy =
[
    [ "wayland::detail::basic_wrapper< native_t >", "classwayland_1_1detail_1_1basic__wrapper.html", null ],
    [ "wayland::detail::basic_wrapper< wl_cursor >", "classwayland_1_1detail_1_1basic__wrapper.html", null ],
    [ "wayland::detail::basic_wrapper< wl_cursor_image >", "classwayland_1_1detail_1_1basic__wrapper.html", null ],
    [ "wayland::data_device_manager_dnd_action", "structwayland_1_1data__device__manager__dnd__action.html", null ],
    [ "wayland::output_mode", "structwayland_1_1output__mode.html", null ],
    [ "wayland::output_transform", "structwayland_1_1output__transform.html", null ],
    [ "wayland::presentation_feedback_kind", "structwayland_1_1presentation__feedback__kind.html", null ],
    [ "wayland::proxy_t", "classwayland_1_1proxy__t.html", [
      [ "wayland::buffer_t", "classwayland_1_1buffer__t.html", null ],
      [ "wayland::callback_t", "classwayland_1_1callback__t.html", null ],
      [ "wayland::compositor_t", "classwayland_1_1compositor__t.html", null ],
      [ "wayland::data_device_manager_t", "classwayland_1_1data__device__manager__t.html", null ],
      [ "wayland::data_device_t", "classwayland_1_1data__device__t.html", null ],
      [ "wayland::data_offer_t", "classwayland_1_1data__offer__t.html", null ],
      [ "wayland::data_source_t", "classwayland_1_1data__source__t.html", null ],
      [ "wayland::display_t", "classwayland_1_1display__t.html", null ],
      [ "wayland::keyboard_t", "classwayland_1_1keyboard__t.html", null ],
      [ "wayland::output_t", "classwayland_1_1output__t.html", null ],
      [ "wayland::pointer_t", "classwayland_1_1pointer__t.html", null ],
      [ "wayland::presentation_feedback_t", "classwayland_1_1presentation__feedback__t.html", null ],
      [ "wayland::presentation_t", "classwayland_1_1presentation__t.html", null ],
      [ "wayland::region_t", "classwayland_1_1region__t.html", null ],
      [ "wayland::registry_t", "classwayland_1_1registry__t.html", null ],
      [ "wayland::seat_t", "classwayland_1_1seat__t.html", null ],
      [ "wayland::shell_surface_t", "classwayland_1_1shell__surface__t.html", null ],
      [ "wayland::shell_t", "classwayland_1_1shell__t.html", null ],
      [ "wayland::shm_pool_t", "classwayland_1_1shm__pool__t.html", null ],
      [ "wayland::shm_t", "classwayland_1_1shm__t.html", null ],
      [ "wayland::subcompositor_t", "classwayland_1_1subcompositor__t.html", null ],
      [ "wayland::subsurface_t", "classwayland_1_1subsurface__t.html", null ],
      [ "wayland::surface_t", "classwayland_1_1surface__t.html", null ],
      [ "wayland::touch_t", "classwayland_1_1touch__t.html", null ],
      [ "wayland::viewport_t", "classwayland_1_1viewport__t.html", null ],
      [ "wayland::viewporter_t", "classwayland_1_1viewporter__t.html", null ],
      [ "wayland::xdg_popup_t", "classwayland_1_1xdg__popup__t.html", null ],
      [ "wayland::xdg_positioner_t", "classwayland_1_1xdg__positioner__t.html", null ],
      [ "wayland::xdg_surface_t", "classwayland_1_1xdg__surface__t.html", null ],
      [ "wayland::xdg_toplevel_t", "classwayland_1_1xdg__toplevel__t.html", null ],
      [ "wayland::xdg_wm_base_t", "classwayland_1_1xdg__wm__base__t.html", null ],
      [ "wayland::zwp_confined_pointer_v1_t", "classwayland_1_1zwp__confined__pointer__v1__t.html", null ],
      [ "wayland::zwp_fullscreen_shell_v1_t", "classwayland_1_1zwp__fullscreen__shell__v1__t.html", null ],
      [ "wayland::zwp_idle_inhibit_manager_v1_t", "classwayland_1_1zwp__idle__inhibit__manager__v1__t.html", null ],
      [ "wayland::zwp_idle_inhibitor_v1_t", "classwayland_1_1zwp__idle__inhibitor__v1__t.html", null ],
      [ "wayland::zwp_input_method_context_v1_t", "classwayland_1_1zwp__input__method__context__v1__t.html", null ],
      [ "wayland::zwp_input_method_v1_t", "classwayland_1_1zwp__input__method__v1__t.html", null ],
      [ "wayland::zwp_input_panel_v1_t", "classwayland_1_1zwp__input__panel__v1__t.html", null ],
      [ "wayland::zwp_input_timestamps_manager_v1_t", "classwayland_1_1zwp__input__timestamps__manager__v1__t.html", null ],
      [ "wayland::zwp_input_timestamps_v1_t", "classwayland_1_1zwp__input__timestamps__v1__t.html", null ],
      [ "wayland::zwp_keyboard_shortcuts_inhibit_manager_v1_t", "classwayland_1_1zwp__keyboard__shortcuts__inhibit__manager__v1__t.html", null ],
      [ "wayland::zwp_keyboard_shortcuts_inhibitor_v1_t", "classwayland_1_1zwp__keyboard__shortcuts__inhibitor__v1__t.html", null ],
      [ "wayland::zwp_linux_buffer_params_v1_t", "classwayland_1_1zwp__linux__buffer__params__v1__t.html", null ],
      [ "wayland::zwp_linux_buffer_release_v1_t", "classwayland_1_1zwp__linux__buffer__release__v1__t.html", null ],
      [ "wayland::zwp_linux_dmabuf_v1_t", "classwayland_1_1zwp__linux__dmabuf__v1__t.html", null ],
      [ "wayland::zwp_linux_explicit_synchronization_v1_t", "classwayland_1_1zwp__linux__explicit__synchronization__v1__t.html", null ],
      [ "wayland::zwp_linux_surface_synchronization_v1_t", "classwayland_1_1zwp__linux__surface__synchronization__v1__t.html", null ],
      [ "wayland::zwp_locked_pointer_v1_t", "classwayland_1_1zwp__locked__pointer__v1__t.html", null ],
      [ "wayland::zwp_pointer_constraints_v1_t", "classwayland_1_1zwp__pointer__constraints__v1__t.html", null ],
      [ "wayland::zwp_pointer_gesture_pinch_v1_t", "classwayland_1_1zwp__pointer__gesture__pinch__v1__t.html", null ],
      [ "wayland::zwp_pointer_gesture_swipe_v1_t", "classwayland_1_1zwp__pointer__gesture__swipe__v1__t.html", null ],
      [ "wayland::zwp_pointer_gestures_v1_t", "classwayland_1_1zwp__pointer__gestures__v1__t.html", null ],
      [ "wayland::zwp_primary_selection_device_manager_v1_t", "classwayland_1_1zwp__primary__selection__device__manager__v1__t.html", null ],
      [ "wayland::zwp_primary_selection_offer_v1_t", "classwayland_1_1zwp__primary__selection__offer__v1__t.html", null ],
      [ "wayland::zwp_primary_selection_source_v1_t", "classwayland_1_1zwp__primary__selection__source__v1__t.html", null ],
      [ "wayland::zwp_relative_pointer_manager_v1_t", "classwayland_1_1zwp__relative__pointer__manager__v1__t.html", null ],
      [ "wayland::zwp_relative_pointer_v1_t", "classwayland_1_1zwp__relative__pointer__v1__t.html", null ],
      [ "wayland::zwp_tablet_manager_v1_t", "classwayland_1_1zwp__tablet__manager__v1__t.html", null ],
      [ "wayland::zwp_tablet_manager_v2_t", "classwayland_1_1zwp__tablet__manager__v2__t.html", null ],
      [ "wayland::zwp_tablet_pad_group_v2_t", "classwayland_1_1zwp__tablet__pad__group__v2__t.html", null ],
      [ "wayland::zwp_tablet_pad_ring_v2_t", "classwayland_1_1zwp__tablet__pad__ring__v2__t.html", null ],
      [ "wayland::zwp_tablet_pad_strip_v2_t", "classwayland_1_1zwp__tablet__pad__strip__v2__t.html", null ],
      [ "wayland::zwp_tablet_pad_v2_t", "classwayland_1_1zwp__tablet__pad__v2__t.html", null ],
      [ "wayland::zwp_tablet_seat_v1_t", "classwayland_1_1zwp__tablet__seat__v1__t.html", null ],
      [ "wayland::zwp_tablet_seat_v2_t", "classwayland_1_1zwp__tablet__seat__v2__t.html", null ],
      [ "wayland::zwp_tablet_tool_v1_t", "classwayland_1_1zwp__tablet__tool__v1__t.html", null ],
      [ "wayland::zwp_tablet_tool_v2_t", "classwayland_1_1zwp__tablet__tool__v2__t.html", null ],
      [ "wayland::zwp_tablet_v1_t", "classwayland_1_1zwp__tablet__v1__t.html", null ],
      [ "wayland::zwp_tablet_v2_t", "classwayland_1_1zwp__tablet__v2__t.html", null ],
      [ "wayland::zwp_text_input_manager_v1_t", "classwayland_1_1zwp__text__input__manager__v1__t.html", null ],
      [ "wayland::zwp_text_input_manager_v3_t", "classwayland_1_1zwp__text__input__manager__v3__t.html", null ],
      [ "wayland::zwp_text_input_v1_t", "classwayland_1_1zwp__text__input__v1__t.html", null ],
      [ "wayland::zwp_text_input_v3_t", "classwayland_1_1zwp__text__input__v3__t.html", null ],
      [ "wayland::zwp_xwayland_keyboard_grab_manager_v1_t", "classwayland_1_1zwp__xwayland__keyboard__grab__manager__v1__t.html", null ],
      [ "wayland::zwp_xwayland_keyboard_grab_v1_t", "classwayland_1_1zwp__xwayland__keyboard__grab__v1__t.html", null ],
      [ "wayland::zxdg_decoration_manager_v1_t", "classwayland_1_1zxdg__decoration__manager__v1__t.html", null ],
      [ "wayland::zxdg_exported_v1_t", "classwayland_1_1zxdg__exported__v1__t.html", null ],
      [ "wayland::zxdg_exported_v2_t", "classwayland_1_1zxdg__exported__v2__t.html", null ],
      [ "wayland::zxdg_exporter_v1_t", "classwayland_1_1zxdg__exporter__v1__t.html", null ],
      [ "wayland::zxdg_exporter_v2_t", "classwayland_1_1zxdg__exporter__v2__t.html", null ],
      [ "wayland::zxdg_imported_v1_t", "classwayland_1_1zxdg__imported__v1__t.html", null ],
      [ "wayland::zxdg_imported_v2_t", "classwayland_1_1zxdg__imported__v2__t.html", null ],
      [ "wayland::zxdg_importer_v1_t", "classwayland_1_1zxdg__importer__v1__t.html", null ],
      [ "wayland::zxdg_importer_v2_t", "classwayland_1_1zxdg__importer__v2__t.html", null ],
      [ "wayland::zxdg_output_manager_v1_t", "classwayland_1_1zxdg__output__manager__v1__t.html", null ],
      [ "wayland::zxdg_output_v1_t", "classwayland_1_1zxdg__output__v1__t.html", null ],
      [ "wayland::zxdg_popup_v6_t", "classwayland_1_1zxdg__popup__v6__t.html", null ],
      [ "wayland::zxdg_positioner_v6_t", "classwayland_1_1zxdg__positioner__v6__t.html", null ],
      [ "wayland::zxdg_shell_v6_t", "classwayland_1_1zxdg__shell__v6__t.html", null ],
      [ "wayland::zxdg_surface_v6_t", "classwayland_1_1zxdg__surface__v6__t.html", null ],
      [ "wayland::zxdg_toplevel_decoration_v1_t", "classwayland_1_1zxdg__toplevel__decoration__v1__t.html", null ],
      [ "wayland::zxdg_toplevel_v6_t", "classwayland_1_1zxdg__toplevel__v6__t.html", null ]
    ] ],
    [ "wayland::read_intent", "classwayland_1_1read__intent.html", null ],
    [ "wayland::detail::refcounted_wrapper< native_t >", "classwayland_1_1detail_1_1refcounted__wrapper.html", null ],
    [ "wayland::detail::refcounted_wrapper< wl_cursor_theme >", "classwayland_1_1detail_1_1refcounted__wrapper.html", null ],
    [ "wayland::detail::refcounted_wrapper< wl_egl_window >", "classwayland_1_1detail_1_1refcounted__wrapper.html", [
      [ "wayland::egl_window_t", "classwayland_1_1egl__window__t.html", null ]
    ] ],
    [ "wayland::detail::refcounted_wrapper< wl_event_queue >", "classwayland_1_1detail_1_1refcounted__wrapper.html", [
      [ "wayland::event_queue_t", "classwayland_1_1event__queue__t.html", null ]
    ] ],
    [ "wayland::seat_capability", "structwayland_1_1seat__capability.html", null ],
    [ "wayland::shell_surface_resize", "structwayland_1_1shell__surface__resize.html", null ],
    [ "wayland::shell_surface_transient", "structwayland_1_1shell__surface__transient.html", null ],
    [ "wayland::xdg_positioner_constraint_adjustment", "structwayland_1_1xdg__positioner__constraint__adjustment.html", null ],
    [ "wayland::xdg_toplevel_resize_edge", "structwayland_1_1xdg__toplevel__resize__edge.html", null ],
    [ "wayland::zwp_text_input_v3_content_hint", "structwayland_1_1zwp__text__input__v3__content__hint.html", null ],
    [ "wayland::zxdg_positioner_v6_constraint_adjustment", "structwayland_1_1zxdg__positioner__v6__constraint__adjustment.html", null ],
    [ "wayland::zxdg_toplevel_v6_resize_edge", "structwayland_1_1zxdg__toplevel__v6__resize__edge.html", null ]
];